//! Companion LD_PRELOAD .so for resolving hook handler addresses at runtime.
//!
//! When hooks reference handler functions in a user-supplied .so (via `handler`
//! in the hook config), the rewritten binary needs a companion preload library
//! that dlopen()s the user's .so, dlsym()s each handler, and writes the resolved
//! function pointers to the data slots in the rewritten binary's new segment.
//!
//! This module generates the C source for that companion .so and compiles it.

use std::path::{Path, PathBuf};

use anyhow::{Context, Result, bail};

use crate::hooks::{HookSource, ResolvedHook};

/// Information needed to generate the companion .so.
pub struct HookPreloadSpec {
    /// Absolute path to the user's hook library .so/.dylib.
    pub library_path: String,
    /// Handler symbols and their corresponding data slot VAs in the rewritten binary.
    pub handlers: Vec<(String, u64)>,
    /// Toggle byte VAs: (toggle_index, toggle_va) for each hook.
    /// Used to write initial toggle values from the companion .so.
    pub toggle_vas: Vec<(usize, u64)>,
    /// Whether the rewritten binary is PIE (position-independent executable).
    pub is_pie: bool,
    /// Whether the target is a Mach-O binary (macOS).
    pub is_macho: bool,
}

/// Build a HookPreloadSpec from resolved hooks and config.
pub fn build_preload_spec(
    hooks: &[ResolvedHook],
    library_path: &Path,
    hook_data_va: u64,
    toggle_data_va: u64,
    is_pie: bool,
    is_macho: bool,
) -> Option<HookPreloadSpec> {
    let mut handlers = Vec::new();
    let mut toggle_vas = Vec::new();

    for hook in hooks {
        if let HookSource::LibrarySymbol {
            ref name,
            data_slot_index,
        } = hook.source
        {
            let slot_va = hook_data_va + (data_slot_index as u64) * 8;
            handlers.push((name.clone(), slot_va));
        }
        let tva = toggle_data_va + hook.toggle_index as u64;
        toggle_vas.push((hook.toggle_index, tva));
    }

    if handlers.is_empty() {
        return None;
    }

    Some(HookPreloadSpec {
        library_path: library_path.to_string_lossy().into_owned(),
        handlers,
        toggle_vas,
        is_pie,
        is_macho,
    })
}

/// Generate C source for the companion preload library.
fn generate_source(spec: &HookPreloadSpec) -> String {
    let mut src = String::with_capacity(2048);

    src.push_str(
        r#"/* truant hook companion -- preload handler resolver.
 * Generated by: truant rewrite --hooks
 * Resolves hook handler symbols and writes function pointers to data slots.
 */
#define _GNU_SOURCE
#include <dlfcn.h>
#include <stdio.h>
#include <stdint.h>
#include <stdlib.h>
#include <string.h>
"#,
    );

    if spec.is_macho {
        src.push_str(
            r#"
#include <mach/mach.h>
#include <mach/mach_vm.h>

/* Write to a code-signed page using the mach_vm_remap alias technique.
 *
 * On ARM64 macOS, code-signing enforcement prevents ALL writes to pages
 * belonging to a signed binary — vm_protect, mprotect, and mmap(MAP_FIXED)
 * all fail.  The workaround (used by Frida, Substrate, etc.) is:
 *   1. mach_vm_remap() creates a second virtual mapping to the same physical
 *      page(s) — this alias is NOT covered by the code signature.
 *   2. vm_protect() on the alias to make it writable.
 *   3. Write through the alias — this modifies the underlying physical page.
 *   4. Deallocate the alias (the original mapping still sees the writes). */
static int write_via_remap(uintptr_t addr, const void *src, size_t len) {
    mach_port_t task = mach_task_self();
    uintptr_t page_sz = (uintptr_t)vm_page_size;
    uintptr_t page_mask = page_sz - 1;
    uintptr_t page = addr & ~page_mask;
    uintptr_t end  = (addr + len + page_mask) & ~page_mask;
    mach_vm_size_t region_sz = end - page;
    uintptr_t offset_in_page = addr - page;
    kern_return_t kr;

    /* Step 1: create a shared alias of the target page(s). */
    mach_vm_address_t alias = 0;
    vm_prot_t cur_prot, max_prot;
    kr = mach_vm_remap(task, &alias, region_sz, 0,
                       VM_FLAGS_ANYWHERE,
                       task, (mach_vm_address_t)page,
                       FALSE, /* copy=FALSE → shared mapping */
                       &cur_prot, &max_prot, VM_INHERIT_NONE);
    if (kr != KERN_SUCCESS) {
        fprintf(stderr, "truant hook: mach_vm_remap(0x%lx, 0x%lx) failed: %s\n",
                (unsigned long)page, (unsigned long)region_sz,
                mach_error_string(kr));
        return -1;
    }

    /* Step 2: make the alias writable.
     * First try without changing max_prot. If that fails (e.g. x86_64 macOS
     * where max_prot may not include WRITE), elevate max_prot first. */
    kr = vm_protect(task, (vm_address_t)alias, (vm_size_t)region_sz,
                    0, VM_PROT_READ | VM_PROT_WRITE);
    if (kr != KERN_SUCCESS) {
        /* Elevate max_prot then retry current prot. */
        kr = vm_protect(task, (vm_address_t)alias, (vm_size_t)region_sz,
                        1, VM_PROT_READ | VM_PROT_WRITE | VM_PROT_EXECUTE);
        if (kr == KERN_SUCCESS) {
            kr = vm_protect(task, (vm_address_t)alias, (vm_size_t)region_sz,
                            0, VM_PROT_READ | VM_PROT_WRITE);
        }
        if (kr != KERN_SUCCESS) {
            fprintf(stderr, "truant hook: vm_protect alias(0x%llx) failed: %s\n",
                    (unsigned long long)alias, mach_error_string(kr));
            mach_vm_deallocate(task, alias, region_sz);
            return -1;
        }
    }

    /* Step 3: write through the alias. */
    memcpy((void *)(uintptr_t)(alias + offset_in_page), src, len);

    /* Step 4: deallocate the alias (original mapping retains the writes). */
    mach_vm_deallocate(task, alias, region_sz);
    return 0;
}
"#,
        );
    }

    if spec.is_pie {
        if spec.is_macho {
            src.push_str(
                r#"
#include <mach-o/dyld.h>
#include <mach-o/loader.h>

static uintptr_t find_binary_base(void) {
    /* When loaded via DYLD_INSERT_LIBRARIES, image index 0 may be the
     * preload dylib rather than the main executable.  Iterate images
     * and find the one with filetype == MH_EXECUTE. */
    uint32_t count = _dyld_image_count();
    for (uint32_t i = 0; i < count; i++) {
        const struct mach_header *hdr = _dyld_get_image_header(i);
        if (hdr && hdr->filetype == MH_EXECUTE) {
            return (uintptr_t)_dyld_get_image_vmaddr_slide(i);
        }
    }
    /* Fallback — should never reach here. */
    return (uintptr_t)_dyld_get_image_vmaddr_slide(0);
}
"#,
            );
        } else {
            src.push_str(
                r#"
#include <link.h>

static uintptr_t find_binary_base(void) {
    /* dl_iterate_phdr callback: find the main binary's load base.
     * The main binary is the first entry with an empty name. */
    struct cb_data { uintptr_t base; };
    static int cb(struct dl_phdr_info *info, size_t size, void *data) {
        struct cb_data *d = (struct cb_data *)data;
        if (info->dlpi_name == NULL || info->dlpi_name[0] == '\0') {
            d->base = info->dlpi_addr;
            return 1; /* stop iteration */
        }
        return 0;
    }
    struct cb_data d = { 0 };
    dl_iterate_phdr(cb, &d);
    return d.base;
}
"#,
            );
        }
    }

    src.push_str("\n__attribute__((constructor))\nstatic void truant_hook_init(void) {\n");

    // dlopen the user's hook library
    src.push_str(&format!(
        "    void *lib = dlopen(\"{}\", RTLD_NOW);\n",
        spec.library_path.replace('\\', "\\\\").replace('"', "\\\""),
    ));
    src.push_str("    if (!lib) {\n");
    src.push_str("        fprintf(stderr, \"truant hook: dlopen failed: %s\\n\", dlerror());\n");
    src.push_str("        abort();\n");
    src.push_str("    }\n\n");

    if spec.is_pie {
        src.push_str("    uintptr_t base = find_binary_base();\n\n");
    }

    // For each handler, dlsym and write to the data slot VA.
    // On macOS ARM64, code-signing prevents direct writes to the binary's
    // address space — use write_via_remap() instead.
    for (name, slot_va) in &spec.handlers {
        src.push_str(&format!(
            "    void *{name}_ptr = dlsym(lib, \"{name}\");\n",
            name = name,
        ));
        src.push_str(&format!("    if (!{name}_ptr) {{\n", name = name,));
        src.push_str(&format!(
            "        fprintf(stderr, \"truant hook: dlsym({name}) failed: %s\\n\", dlerror());\n",
            name = name,
        ));
        src.push_str("        abort();\n");
        src.push_str("    }\n");

        if spec.is_macho {
            // Use mach_vm_remap alias technique to write through code-signed pages.
            if spec.is_pie {
                src.push_str(&format!(
                    "    if (write_via_remap(base + 0x{:x}ULL, &{}_ptr, sizeof(void *)) != 0) {{\n",
                    slot_va, name,
                ));
            } else {
                src.push_str(&format!(
                    "    if (write_via_remap(0x{:x}ULL, &{}_ptr, sizeof(void *)) != 0) {{\n",
                    slot_va, name,
                ));
            }
            src.push_str(&format!(
                "        fprintf(stderr, \"truant hook: write_via_remap({}) failed\\n\");\n",
                name,
            ));
            src.push_str("        abort();\n");
            src.push_str("    }\n\n");
        } else if spec.is_pie {
            src.push_str(&format!(
                "    *(void **)(base + 0x{:x}ULL) = {}_ptr;\n\n",
                slot_va, name,
            ));
        } else {
            src.push_str(&format!(
                "    *(void **)(0x{:x}ULL) = {}_ptr;\n\n",
                slot_va, name,
            ));
        }
    }

    // Write initial toggle values alongside handler pointers.
    // Toggle bytes are already initialised in the segment data, but when PIE is
    // active the companion .so can also verify/reinforce the toggle state at
    // runtime (useful for debuggers that want to flip toggles).
    if !spec.toggle_vas.is_empty() {
        src.push_str("    /* Toggle bytes are initialised in the rewritten binary's\n");
        src.push_str("     * data segment.  No runtime action needed here. */\n");
    }

    src.push_str("}\n");
    src
}

/// Generate the companion preload .so.
///
/// Writes a C source file next to `output_path`, compiles it, and returns
/// the path to the resulting `.so`.
pub fn generate_hook_preload_lib(
    output_path: &Path,
    spec: &HookPreloadSpec,
    is_macho: bool,
) -> Result<PathBuf> {
    let lib_path = hook_preload_lib_path(output_path, is_macho);
    let src_path = lib_path.with_extension("c");

    let source = generate_source(spec);
    std::fs::write(&src_path, &source)
        .with_context(|| format!("failed to write {}", src_path.display()))?;

    let compilers = ["cc", "gcc", "clang"];
    let mut last_err = String::new();

    let compile_args: Vec<&str> = if is_macho {
        vec!["-dynamiclib", "-O2", "-ldl"]
    } else {
        vec!["-shared", "-fPIC", "-O2", "-ldl"]
    };

    for compiler in &compilers {
        let result = std::process::Command::new(compiler)
            .args(&compile_args)
            .args(["-o", lib_path.to_str().unwrap_or("")])
            .arg(src_path.to_str().unwrap_or(""))
            .output();

        match result {
            Ok(output) if output.status.success() => {
                tracing::info!(
                    "hook preload: compiled companion library {} ({} bytes)",
                    lib_path.display(),
                    std::fs::metadata(&lib_path).map(|m| m.len()).unwrap_or(0),
                );
                return Ok(lib_path);
            }
            Ok(output) => {
                last_err = String::from_utf8_lossy(&output.stderr).into_owned();
            }
            Err(e) => {
                last_err = e.to_string();
            }
        }
    }

    let _ = std::fs::remove_file(&src_path);
    bail!(
        "failed to compile hook companion preload library (tried: {}): {}",
        compilers.join(", "),
        last_err,
    );
}

/// Compute the path for the hook preload library.
pub fn hook_preload_lib_path(output_path: &Path, is_macho: bool) -> PathBuf {
    let mut name = output_path.file_name().unwrap_or_default().to_os_string();
    if is_macho {
        name.push(".hook_preload.dylib");
    } else {
        name.push(".hook_preload.so");
    }
    output_path.with_file_name(name)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_hook_preload_lib_path() {
        let p = hook_preload_lib_path(Path::new("/tmp/foo.rewritten"), false);
        assert_eq!(p, PathBuf::from("/tmp/foo.rewritten.hook_preload.so"));
    }

    #[test]
    fn test_hook_preload_lib_path_macho() {
        let p = hook_preload_lib_path(Path::new("/tmp/foo.rewritten"), true);
        assert_eq!(p, PathBuf::from("/tmp/foo.rewritten.hook_preload.dylib"));
    }

    #[test]
    fn test_generate_source_non_pie() {
        let spec = HookPreloadSpec {
            library_path: "./my_hooks.so".to_string(),
            handlers: vec![
                ("my_pre_hook".to_string(), 0x600100),
                ("my_replace".to_string(), 0x600108),
            ],
            toggle_vas: vec![(0, 0x600200), (1, 0x600201)],
            is_pie: false,
            is_macho: false,
        };
        let src = generate_source(&spec);
        assert!(src.contains("dlopen(\"./my_hooks.so\""));
        assert!(src.contains("dlsym(lib, \"my_pre_hook\")"));
        assert!(src.contains("dlsym(lib, \"my_replace\")"));
        assert!(src.contains("0x600100"));
        assert!(src.contains("0x600108"));
        assert!(!src.contains("find_binary_base"));
    }

    #[test]
    fn test_generate_source_pie() {
        let spec = HookPreloadSpec {
            library_path: "/opt/hooks/libhook.so".to_string(),
            handlers: vec![("handler_a".to_string(), 0x22000)],
            toggle_vas: vec![(0, 0x22100)],
            is_pie: true,
            is_macho: false,
        };
        let src = generate_source(&spec);
        assert!(src.contains("find_binary_base"));
        assert!(src.contains("dl_iterate_phdr"));
        assert!(src.contains("base + 0x22000"));
    }

    #[test]
    fn test_generate_source_pie_macho() {
        let spec = HookPreloadSpec {
            library_path: "/opt/hooks/libhook.dylib".to_string(),
            handlers: vec![("handler_a".to_string(), 0x22000)],
            toggle_vas: vec![(0, 0x22100)],
            is_pie: true,
            is_macho: true,
        };
        let src = generate_source(&spec);
        assert!(src.contains("find_binary_base"));
        assert!(src.contains("_dyld_get_image_vmaddr_slide"));
        assert!(!src.contains("dl_iterate_phdr"));
        assert!(src.contains("base + 0x22000"));
        // Must use mach_vm_remap alias technique on macOS
        assert!(
            src.contains("write_via_remap"),
            "macOS source must use write_via_remap()"
        );
        assert!(
            src.contains("mach_vm_remap"),
            "macOS source must use mach_vm_remap"
        );
        assert!(
            src.contains("mach/mach_vm.h"),
            "macOS source must include mach/mach_vm.h"
        );
    }

    #[test]
    fn test_build_preload_spec_no_library_hooks() {
        let hooks = vec![ResolvedHook {
            target_va: 0x401000,
            file_offset: 0x1000,
            displaced_bytes: vec![0x90; 5],
            displaced_len: 5,
            mode: crate::hooks::HookMode::Pre,
            source: HookSource::Shellcode(vec![0xC3]),
            condition: None,
            toggle_index: 0,
            initial_enabled: true,
            return_slot_index: None,
        }];
        assert!(
            build_preload_spec(
                &hooks,
                Path::new("./lib.so"),
                0x500000,
                0x500100,
                false,
                false
            )
            .is_none()
        );
    }

    #[test]
    fn test_build_preload_spec_with_library_hooks() {
        let hooks = vec![ResolvedHook {
            target_va: 0x401000,
            file_offset: 0x1000,
            displaced_bytes: vec![0x90; 5],
            displaced_len: 5,
            mode: crate::hooks::HookMode::Pre,
            source: HookSource::LibrarySymbol {
                name: "my_hook".to_string(),
                data_slot_index: 0,
            },
            condition: None,
            toggle_index: 0,
            initial_enabled: true,
            return_slot_index: None,
        }];
        let spec = build_preload_spec(
            &hooks,
            Path::new("./lib.so"),
            0x500000,
            0x500100,
            false,
            false,
        );
        assert!(spec.is_some());
        let spec = spec.expect("hook library spec should be Some");
        assert_eq!(spec.handlers.len(), 1);
        assert_eq!(spec.handlers[0].0, "my_hook");
        assert_eq!(spec.handlers[0].1, 0x500000);
    }
}
