//! LD_PRELOAD guard-page heap sanitiser for dynamically linked binaries.
//!
//! Generates a small C source file and compiles it into a shared library that
//! overrides malloc/free/calloc/realloc/memalign/aligned_alloc/posix_memalign.
//! Every allocation uses mmap + a trailing PROT_NONE guard page; free marks
//! the entire region PROT_NONE. This catches heap-buffer-overflow, use-after-free,
//! and double-free via SIGSEGV.
//!
//! Unlike GOT patching (which only intercepts calls through the main binary's PLT),
//! LD_PRELOAD overrides allocator symbols globally across all shared libraries.

use std::path::{Path, PathBuf};

use anyhow::{Context, Result, bail};

/// C source for the LD_PRELOAD heap sanitiser (Linux/ELF).
///
/// Uses raw syscalls via `syscall()` — the libc wrapper is a thin shim that
/// doesn't allocate, so it's safe to call from within our malloc implementation.
const PRELOAD_SOURCE: &str = r#"/* truant heap sanitiser -- LD_PRELOAD guard-page allocator.
 * Generated by: truant rewrite --heap-san
 * All allocations use mmap + guard page; free uses mprotect(PROT_NONE).
 */
#define _GNU_SOURCE
#include <stddef.h>
#include <stdint.h>
#include <unistd.h>
#include <sys/syscall.h>

#define PAGE_SIZE 4096
#define MAGIC 0x545255414E544853ULL /* "TRUANTHS" */

struct heap_meta {
    uint64_t magic;
    void    *mmap_base;
    uint64_t total_size;
    uint64_t requested_size;
};

static void *raw_mmap(size_t len) {
    return (void *)syscall(SYS_mmap, (void *)0, len,
                           3 /* PROT_READ|PROT_WRITE */,
                           0x22 /* MAP_PRIVATE|MAP_ANONYMOUS */,
                           -1, (off_t)0);
}

static int raw_mprotect(void *addr, size_t len, int prot) {
    return (int)syscall(SYS_mprotect, addr, len, prot);
}

static void *guard_alloc(size_t size, size_t alignment) {
    if (alignment < 16) alignment = 16;
    size_t data_pages = (size + 32 + alignment + PAGE_SIZE - 1) & ~(size_t)(PAGE_SIZE - 1);
    size_t total = data_pages + PAGE_SIZE;

    void *base = raw_mmap(total);
    if ((intptr_t)base < 0 && (intptr_t)base >= -4096)
        return (void *)0;

    raw_mprotect((char *)base + data_pages, PAGE_SIZE, 0 /* PROT_NONE */);

    uintptr_t raw_ptr = (uintptr_t)base + data_pages - size;
    uintptr_t user_ptr = raw_ptr & ~(alignment - 1);

    struct heap_meta *meta = (struct heap_meta *)(user_ptr - 32);
    meta->magic          = MAGIC;
    meta->mmap_base      = base;
    meta->total_size     = total;
    meta->requested_size = size;

    return (void *)user_ptr;
}

static struct heap_meta *get_meta(void *ptr) {
    if (!ptr || (uintptr_t)ptr < PAGE_SIZE) return (void *)0;
    struct heap_meta *m = (struct heap_meta *)((uintptr_t)ptr - 32);
    if (m->magic != MAGIC) return (void *)0;
    return m;
}

void *malloc(size_t size) {
    return guard_alloc(size, 16);
}

void free(void *ptr) {
    struct heap_meta *meta = get_meta(ptr);
    if (!meta) return;
    raw_mprotect(meta->mmap_base, meta->total_size, 0);
}

void *calloc(size_t count, size_t size) {
    /* Overflow check */
    if (count && size > (size_t)-1 / count)
        return (void *)0;
    size_t total = count * size;
    /* mmap returns zeroed pages, no memset needed */
    return guard_alloc(total, 16);
}

void *realloc(void *ptr, size_t new_size) {
    if (!ptr) return guard_alloc(new_size, 16);
    if (!new_size) { free(ptr); return (void *)0; }

    struct heap_meta *meta = get_meta(ptr);
    size_t old_size = meta ? meta->requested_size : 0;

    void *new_ptr = guard_alloc(new_size, 16);
    if (!new_ptr) return (void *)0;

    if (old_size > 0) {
        size_t n = old_size < new_size ? old_size : new_size;
        const char *s = (const char *)ptr;
        char *d = (char *)new_ptr;
        for (size_t i = 0; i < n; i++) d[i] = s[i];
        free(ptr);
    }
    return new_ptr;
}

void *memalign(size_t alignment, size_t size) {
    return guard_alloc(size, alignment);
}

void *aligned_alloc(size_t alignment, size_t size) {
    return guard_alloc(size, alignment);
}

int posix_memalign(void **memptr, size_t alignment, size_t size) {
    void *p = guard_alloc(size, alignment);
    if (!p) return 12; /* ENOMEM */
    *memptr = p;
    return 0;
}
"#;

/// C source for the DYLD_INSERT_LIBRARIES heap sanitiser (macOS/Mach-O).
///
/// Uses `__DATA,__interpose` sections for symbol interposition (macOS dyld API)
/// instead of ELF LD_PRELOAD symbol override. Uses `dlsym(RTLD_NEXT, ...)` to
/// get original function pointers for realloc copy.
const PRELOAD_SOURCE_MACOS: &str = r#"/* truant heap sanitiser -- DYLD_INSERT_LIBRARIES guard-page allocator.
 * Generated by: truant rewrite --heap-san (macOS)
 * All allocations use mmap + guard page; free uses mprotect(PROT_NONE).
 */
#include <stddef.h>
#include <stdint.h>
#include <unistd.h>
#include <sys/mman.h>
#include <dlfcn.h>

#define PAGE_SIZE 4096
#define MAGIC 0x545255414E544853ULL /* "TRUANTHS" */

struct heap_meta {
    uint64_t magic;
    void    *mmap_base;
    uint64_t total_size;
    uint64_t requested_size;
};

static void *raw_mmap(size_t len) {
    return mmap(NULL, len, PROT_READ | PROT_WRITE,
                MAP_PRIVATE | MAP_ANONYMOUS, -1, 0);
}

static void *guard_alloc(size_t size, size_t alignment) {
    if (alignment < 16) alignment = 16;
    size_t data_pages = (size + 32 + alignment + PAGE_SIZE - 1) & ~(size_t)(PAGE_SIZE - 1);
    size_t total = data_pages + PAGE_SIZE;

    void *base = raw_mmap(total);
    if (base == MAP_FAILED)
        return (void *)0;

    mprotect((char *)base + data_pages, PAGE_SIZE, PROT_NONE);

    uintptr_t raw_ptr = (uintptr_t)base + data_pages - size;
    uintptr_t user_ptr = raw_ptr & ~(alignment - 1);

    struct heap_meta *meta = (struct heap_meta *)(user_ptr - 32);
    meta->magic          = MAGIC;
    meta->mmap_base      = base;
    meta->total_size     = total;
    meta->requested_size = size;

    return (void *)user_ptr;
}

static struct heap_meta *get_meta(void *ptr) {
    if (!ptr || (uintptr_t)ptr < PAGE_SIZE) return (void *)0;
    struct heap_meta *m = (struct heap_meta *)((uintptr_t)ptr - 32);
    if (m->magic != MAGIC) return (void *)0;
    return m;
}

void *truant_malloc(size_t size) {
    return guard_alloc(size, 16);
}

void truant_free(void *ptr) {
    struct heap_meta *meta = get_meta(ptr);
    if (!meta) return;
    mprotect(meta->mmap_base, meta->total_size, PROT_NONE);
}

void *truant_calloc(size_t count, size_t size) {
    if (count && size > (size_t)-1 / count)
        return (void *)0;
    size_t total = count * size;
    return guard_alloc(total, 16);
}

void *truant_realloc(void *ptr, size_t new_size) {
    if (!ptr) return guard_alloc(new_size, 16);
    if (!new_size) { truant_free(ptr); return (void *)0; }

    struct heap_meta *meta = get_meta(ptr);
    size_t old_size = meta ? meta->requested_size : 0;

    void *new_ptr = guard_alloc(new_size, 16);
    if (!new_ptr) return (void *)0;

    if (old_size > 0) {
        size_t n = old_size < new_size ? old_size : new_size;
        const char *s = (const char *)ptr;
        char *d = (char *)new_ptr;
        for (size_t i = 0; i < n; i++) d[i] = s[i];
        truant_free(ptr);
    }
    return new_ptr;
}

void *truant_memalign(size_t alignment, size_t size) {
    return guard_alloc(size, alignment);
}

int truant_posix_memalign(void **memptr, size_t alignment, size_t size) {
    void *p = guard_alloc(size, alignment);
    if (!p) return 12; /* ENOMEM */
    *memptr = p;
    return 0;
}

/* macOS dyld interposition via __DATA,__interpose */
typedef struct { void *replacement; void *original; } interpose_t;

__attribute__((used)) static const interpose_t interpose_malloc
    __attribute__((section("__DATA,__interpose"))) = { (void *)truant_malloc, (void *)malloc };
__attribute__((used)) static const interpose_t interpose_free
    __attribute__((section("__DATA,__interpose"))) = { (void *)truant_free, (void *)free };
__attribute__((used)) static const interpose_t interpose_calloc
    __attribute__((section("__DATA,__interpose"))) = { (void *)truant_calloc, (void *)calloc };
__attribute__((used)) static const interpose_t interpose_realloc
    __attribute__((section("__DATA,__interpose"))) = { (void *)truant_realloc, (void *)realloc };
__attribute__((used)) static const interpose_t interpose_posix_memalign
    __attribute__((section("__DATA,__interpose"))) = { (void *)truant_posix_memalign, (void *)posix_memalign };
"#;

/// Generate the heap sanitiser shared library (preload-based).
///
/// Writes a C source file next to `output_path`, compiles it with `cc`, and
/// returns the path to the resulting `.so` (Linux) or `.dylib` (macOS).
pub fn generate_preload_lib(output_path: &Path, is_macho: bool) -> Result<PathBuf> {
    let lib_path = preload_lib_path(output_path, is_macho);
    let src_path = lib_path.with_extension("c");

    let source = if is_macho {
        PRELOAD_SOURCE_MACOS
    } else {
        PRELOAD_SOURCE
    };
    std::fs::write(&src_path, source)
        .with_context(|| format!("failed to write {}", src_path.display()))?;

    let compilers = ["cc", "gcc", "clang"];
    let mut last_err = String::new();

    let compile_args: &[&str] = if is_macho {
        &["-dynamiclib", "-O2"]
    } else {
        &["-shared", "-fPIC", "-O2"]
    };

    for compiler in &compilers {
        let result = std::process::Command::new(compiler)
            .args(compile_args)
            .args(["-o", lib_path.to_str().unwrap_or("")])
            .arg(src_path.to_str().unwrap_or(""))
            .output();

        match result {
            Ok(output) if output.status.success() => {
                let _ = std::fs::remove_file(&src_path);
                tracing::info!(
                    "heap san: compiled preload library {} ({} bytes)",
                    lib_path.display(),
                    std::fs::metadata(&lib_path).map(|m| m.len()).unwrap_or(0),
                );
                return Ok(lib_path);
            }
            Ok(output) => {
                last_err = String::from_utf8_lossy(&output.stderr).into_owned();
            }
            Err(e) => {
                last_err = e.to_string();
            }
        }
    }

    let _ = std::fs::remove_file(&src_path);
    bail!(
        "failed to compile heap san preload library (tried: {}): {}",
        compilers.join(", "),
        last_err,
    );
}

/// Compute the path for the preload library based on the rewritten binary path.
pub fn preload_lib_path(output_path: &Path, is_macho: bool) -> PathBuf {
    let mut name = output_path.file_name().unwrap_or_default().to_os_string();
    if is_macho {
        name.push(".heap_san.dylib");
    } else {
        name.push(".heap_san.so");
    }
    output_path.with_file_name(name)
}

/// C source for the Windows DLL heap sanitiser.
///
/// Cross-compiled with `x86_64-w64-mingw32-gcc` (or `i686-w64-mingw32-gcc` for 32-bit).
/// Uses `VirtualAlloc`/`VirtualProtect` for guard-page allocation.
/// Exports `truant_heap_san_init` for IAT import injection.
const PRELOAD_SOURCE_WINDOWS: &str = r#"/* truant heap sanitiser -- guard-page allocator DLL.
 * Generated by: truant rewrite --heap-san
 * Cross-compiled for Windows. Loaded via IAT import injection.
 */
#include <windows.h>
#include <stdint.h>

#define PAGE_SIZE 4096
#define MAGIC 0x5452554E54485355ULL /* "TRUANTHS" */

struct heap_meta {
    uint64_t magic;
    void    *alloc_base;
    uint64_t total_size;
    uint64_t requested_size;
};

static void *guard_alloc(size_t size, size_t alignment) {
    if (alignment < 16) alignment = 16;
    size_t data_pages = (size + 32 + alignment + PAGE_SIZE - 1) & ~(size_t)(PAGE_SIZE - 1);
    size_t total = data_pages + PAGE_SIZE;

    void *base = VirtualAlloc(NULL, total, MEM_COMMIT | MEM_RESERVE, PAGE_READWRITE);
    if (!base) return NULL;

    /* Guard page at the end */
    DWORD old_prot;
    VirtualProtect((char *)base + data_pages, PAGE_SIZE, PAGE_NOACCESS, &old_prot);

    uintptr_t raw_ptr = (uintptr_t)base + data_pages - size;
    uintptr_t user_ptr = raw_ptr & ~(alignment - 1);

    struct heap_meta *meta = (struct heap_meta *)(user_ptr - 32);
    meta->magic          = MAGIC;
    meta->alloc_base     = base;
    meta->total_size     = total;
    meta->requested_size = size;

    return (void *)user_ptr;
}

static struct heap_meta *get_meta(void *ptr) {
    if (!ptr || (uintptr_t)ptr < PAGE_SIZE) return NULL;
    struct heap_meta *m = (struct heap_meta *)((uintptr_t)ptr - 32);
    if (m->magic != MAGIC) return NULL;
    return m;
}

/* Original CRT function pointers */
static void *(*orig_malloc)(size_t) = NULL;
static void  (*orig_free)(void *) = NULL;
static void *(*orig_calloc)(size_t, size_t) = NULL;
static void *(*orig_realloc)(void *, size_t) = NULL;

static void resolve_crt(void) {
    HMODULE ucrt = GetModuleHandleA("ucrtbase.dll");
    if (!ucrt) ucrt = GetModuleHandleA("msvcrt.dll");
    if (!ucrt) return;
    orig_malloc  = (void *(*)(size_t))GetProcAddress(ucrt, "malloc");
    orig_free    = (void (*)(void *))GetProcAddress(ucrt, "free");
    orig_calloc  = (void *(*)(size_t, size_t))GetProcAddress(ucrt, "calloc");
    orig_realloc = (void *(*)(void *, size_t))GetProcAddress(ucrt, "realloc");
}

/* Exported functions — override CRT allocator */
__declspec(dllexport) void *truant_malloc(size_t size) {
    return guard_alloc(size, 16);
}

__declspec(dllexport) void truant_free(void *ptr) {
    struct heap_meta *meta = get_meta(ptr);
    if (!meta) {
        /* Not our allocation — forward to original free */
        if (orig_free) orig_free(ptr);
        return;
    }
    DWORD old_prot;
    VirtualProtect(meta->alloc_base, (SIZE_T)meta->total_size, PAGE_NOACCESS, &old_prot);
}

__declspec(dllexport) void *truant_calloc(size_t count, size_t size) {
    if (count && size > (size_t)-1 / count) return NULL;
    size_t total = count * size;
    /* VirtualAlloc returns zeroed pages */
    return guard_alloc(total, 16);
}

__declspec(dllexport) void *truant_realloc(void *ptr, size_t new_size) {
    if (!ptr) return guard_alloc(new_size, 16);
    if (!new_size) { truant_free(ptr); return NULL; }

    struct heap_meta *meta = get_meta(ptr);
    size_t old_size = meta ? (size_t)meta->requested_size : 0;

    void *new_ptr = guard_alloc(new_size, 16);
    if (!new_ptr) return NULL;

    if (old_size > 0) {
        size_t n = old_size < new_size ? old_size : new_size;
        memcpy(new_ptr, ptr, n);
        truant_free(ptr);
    }
    return new_ptr;
}

/* Dummy export for IAT import injection */
__declspec(dllexport) void truant_heap_san_init(void) {}

BOOL WINAPI DllMain(HINSTANCE hDll, DWORD reason, LPVOID reserved) {
    (void)hDll; (void)reserved;
    if (reason == DLL_PROCESS_ATTACH) {
        resolve_crt();
        /* Patch IAT of the main module to redirect malloc/free/etc
         * to our guard-page implementations. */
        HMODULE exe = GetModuleHandleA(NULL);
        if (!exe) return TRUE;

        /* Walk the IAT looking for ucrtbase.dll or msvcrt.dll imports */
        PIMAGE_DOS_HEADER dos = (PIMAGE_DOS_HEADER)exe;
        PIMAGE_NT_HEADERS nt = (PIMAGE_NT_HEADERS)((char *)exe + dos->e_lfanew);
        DWORD import_rva = nt->OptionalHeader.DataDirectory[1].VirtualAddress;
        if (!import_rva) return TRUE;

        PIMAGE_IMPORT_DESCRIPTOR imp = (PIMAGE_IMPORT_DESCRIPTOR)((char *)exe + import_rva);
        for (; imp->Name; imp++) {
            const char *dll_name = (const char *)((char *)exe + imp->Name);
            /* Case-insensitive check for ucrtbase.dll or msvcrt.dll */
            int is_crt = 0;
            if ((dll_name[0] == 'u' || dll_name[0] == 'U') &&
                (dll_name[1] == 'c' || dll_name[1] == 'C')) is_crt = 1;
            if ((dll_name[0] == 'm' || dll_name[0] == 'M') &&
                (dll_name[1] == 's' || dll_name[1] == 'S')) is_crt = 1;
            if (!is_crt) continue;

            PIMAGE_THUNK_DATA orig = (PIMAGE_THUNK_DATA)((char *)exe + imp->OriginalFirstThunk);
            PIMAGE_THUNK_DATA thunk = (PIMAGE_THUNK_DATA)((char *)exe + imp->FirstThunk);

            for (; orig->u1.AddressOfData; orig++, thunk++) {
                if (orig->u1.Ordinal & IMAGE_ORDINAL_FLAG) continue;
                PIMAGE_IMPORT_BY_NAME ibn = (PIMAGE_IMPORT_BY_NAME)((char *)exe + orig->u1.AddressOfData);
                const char *fn = (const char *)ibn->Name;

                void *replacement = NULL;
                if (fn[0] == 'm' && fn[1] == 'a' && fn[2] == 'l' && fn[3] == 'l' &&
                    fn[4] == 'o' && fn[5] == 'c' && fn[6] == '\0')
                    replacement = (void *)truant_malloc;
                else if (fn[0] == 'f' && fn[1] == 'r' && fn[2] == 'e' && fn[3] == 'e' &&
                         fn[4] == '\0')
                    replacement = (void *)truant_free;
                else if (fn[0] == 'c' && fn[1] == 'a' && fn[2] == 'l' && fn[3] == 'l' &&
                         fn[4] == 'o' && fn[5] == 'c' && fn[6] == '\0')
                    replacement = (void *)truant_calloc;
                else if (fn[0] == 'r' && fn[1] == 'e' && fn[2] == 'a' && fn[3] == 'l' &&
                         fn[4] == 'l' && fn[5] == 'o' && fn[6] == 'c' && fn[7] == '\0')
                    replacement = (void *)truant_realloc;

                if (replacement) {
                    DWORD old_prot;
                    VirtualProtect(&thunk->u1.Function, sizeof(uintptr_t), PAGE_READWRITE, &old_prot);
                    thunk->u1.Function = (uintptr_t)replacement;
                    VirtualProtect(&thunk->u1.Function, sizeof(uintptr_t), old_prot, &old_prot);
                }
            }
        }
    }
    return TRUE;
}
"#;

/// Generate the heap sanitiser DLL for Windows PE targets.
///
/// Cross-compiles a C source into a `.dll` using `x86_64-w64-mingw32-gcc`
/// (or `i686-w64-mingw32-gcc` for 32-bit PE). Returns the path to the DLL.
pub fn generate_preload_dll(output_path: &Path, is_32bit: bool) -> Result<PathBuf> {
    let dll_path = preload_dll_path(output_path);
    let src_path = dll_path.with_extension("c");

    std::fs::write(&src_path, PRELOAD_SOURCE_WINDOWS)
        .with_context(|| format!("failed to write {}", src_path.display()))?;

    let compiler = if is_32bit {
        "i686-w64-mingw32-gcc"
    } else {
        "x86_64-w64-mingw32-gcc"
    };

    let result = std::process::Command::new(compiler)
        .args(["-shared", "-O2", "-o"])
        .arg(dll_path.to_str().unwrap_or(""))
        .arg(src_path.to_str().unwrap_or(""))
        .output();

    match result {
        Ok(output) if output.status.success() => {
            let _ = std::fs::remove_file(&src_path);
            tracing::info!(
                "heap san: compiled companion DLL {} ({} bytes)",
                dll_path.display(),
                std::fs::metadata(&dll_path).map(|m| m.len()).unwrap_or(0),
            );
            Ok(dll_path)
        }
        Ok(output) => {
            let stderr = String::from_utf8_lossy(&output.stderr);
            let _ = std::fs::remove_file(&src_path);
            bail!(
                "failed to compile heap san DLL with {}: {}",
                compiler,
                stderr,
            );
        }
        Err(e) => {
            let _ = std::fs::remove_file(&src_path);
            bail!(
                "mingw cross-compiler {} not found: {} (install with: apt install gcc-mingw-w64)",
                compiler,
                e,
            );
        }
    }
}

/// Compute the path for the Windows heap sanitiser DLL.
pub fn preload_dll_path(output_path: &Path) -> PathBuf {
    let mut name = output_path.file_name().unwrap_or_default().to_os_string();
    name.push(".heap_san.dll");
    output_path.with_file_name(name)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_preload_lib_path() {
        let p = preload_lib_path(Path::new("/tmp/foo.rewritten"), false);
        assert_eq!(p, PathBuf::from("/tmp/foo.rewritten.heap_san.so"));
    }

    #[test]
    fn test_preload_lib_path_macho() {
        let p = preload_lib_path(Path::new("/tmp/foo.rewritten"), true);
        assert_eq!(p, PathBuf::from("/tmp/foo.rewritten.heap_san.dylib"));
    }

    #[cfg(target_os = "linux")]
    #[test]
    fn test_generate_preload_lib() {
        let td = tempfile::tempdir().unwrap();
        let output = td.path().join("preload_target");
        let so_path = generate_preload_lib(&output, false).expect("failed to compile preload lib");

        assert!(so_path.exists(), "preload .so should exist");

        // Verify it's a valid shared library.
        let file_output = std::process::Command::new("file")
            .arg(&so_path)
            .output()
            .expect("file command failed");
        let desc = String::from_utf8_lossy(&file_output.stdout);
        assert!(
            desc.contains("shared object"),
            "should be a shared object: {}",
            desc
        );

        // Verify exported symbols.
        let nm_output = std::process::Command::new("nm")
            .args(["-D", so_path.to_str().unwrap()])
            .output()
            .expect("nm command failed");
        let symbols = String::from_utf8_lossy(&nm_output.stdout);
        for name in &[
            "malloc",
            "free",
            "calloc",
            "realloc",
            "memalign",
            "aligned_alloc",
            "posix_memalign",
        ] {
            assert!(symbols.contains(name), "missing exported symbol: {}", name);
        }
    }

    #[cfg(target_os = "linux")]
    #[test]
    fn test_preload_clean_program() {
        // Compile a small test program and run it under our preload .so.
        let td = tempfile::tempdir().unwrap();
        let src = td.path().join("preload_test_clean.c");
        let bin = td.path().join("preload_test_clean");
        std::fs::write(
            &src,
            r#"
#include <stdlib.h>
#include <string.h>
int main() {
    char *a = malloc(64);
    if (!a) return 1;
    memset(a, 'A', 64);
    char *b = realloc(a, 128);
    if (!b) return 2;
    b[127] = 'Z';
    char *c = calloc(16, 8);
    if (!c) return 3;
    void *d = NULL;
    if (posix_memalign(&d, 64, 256)) return 4;
    free(b);
    free(c);
    free(d);
    return 0;
}
"#,
        )
        .unwrap();

        let cc = std::process::Command::new("gcc")
            .args(["-o", bin.to_str().unwrap(), src.to_str().unwrap()])
            .status()
            .expect("gcc not available");
        assert!(cc.success());
        let _ = std::fs::remove_file(&src);

        let so_path = generate_preload_lib(&bin, false).expect("failed to compile preload lib");

        let status = std::process::Command::new(&bin)
            .env("LD_PRELOAD", &so_path)
            .status()
            .expect("failed to run");
        assert!(
            status.success(),
            "clean program should exit 0 under preload, got {:?}",
            status
        );
    }

    #[cfg(target_os = "linux")]
    #[test]
    fn test_preload_overflow() {
        let td = tempfile::tempdir().unwrap();
        let src = td.path().join("preload_test_overflow.c");
        let bin = td.path().join("preload_test_overflow");
        std::fs::write(
            &src,
            r#"
#include <stdlib.h>
int main() {
    char *buf = malloc(16);
    if (!buf) return 1;
    buf[16] = 'X'; /* one byte past end → guard page */
    free(buf);
    return 0;
}
"#,
        )
        .unwrap();

        let cc = std::process::Command::new("gcc")
            .args(["-o", bin.to_str().unwrap(), src.to_str().unwrap()])
            .status()
            .expect("gcc not available");
        assert!(cc.success());
        let _ = std::fs::remove_file(&src);

        let so_path = generate_preload_lib(&bin, false).expect("failed to compile preload lib");

        let status = std::process::Command::new(&bin)
            .env("LD_PRELOAD", &so_path)
            .status()
            .expect("failed to run");

        #[cfg(unix)]
        {
            use std::os::unix::process::ExitStatusExt;
            assert_eq!(
                status.signal(),
                Some(11),
                "overflow should trigger SIGSEGV, got {:?}",
                status
            );
        }
    }

    #[cfg(target_os = "linux")]
    #[test]
    fn test_preload_use_after_free() {
        let td = tempfile::tempdir().unwrap();
        let src = td.path().join("preload_test_uaf.c");
        let bin = td.path().join("preload_test_uaf");
        std::fs::write(
            &src,
            r#"
#include <stdlib.h>
int main() {
    char *buf = malloc(16);
    if (!buf) return 1;
    free(buf);
    buf[0] = 'X'; /* use-after-free → PROT_NONE page */
    return 0;
}
"#,
        )
        .unwrap();

        let cc = std::process::Command::new("gcc")
            .args(["-o", bin.to_str().unwrap(), src.to_str().unwrap()])
            .status()
            .expect("gcc not available");
        assert!(cc.success());
        let _ = std::fs::remove_file(&src);

        let so_path = generate_preload_lib(&bin, false).expect("failed to compile preload lib");

        let status = std::process::Command::new(&bin)
            .env("LD_PRELOAD", &so_path)
            .status()
            .expect("failed to run");

        #[cfg(unix)]
        {
            use std::os::unix::process::ExitStatusExt;
            assert_eq!(
                status.signal(),
                Some(11),
                "use-after-free should trigger SIGSEGV, got {:?}",
                status
            );
        }
    }
}
