//! LD_PRELOAD sidecar memory sanitiser for dynamically linked binaries.
//!
//! Generates a small C source file and compiles it into a shared library that
//! wraps malloc/free/calloc/realloc/memalign/aligned_alloc/posix_memalign
//! and memcpy/memmove/memset/strcpy/strncpy. Each call is logged to a SysV SHM
//! ring buffer that a validator thread in the campaign process reads to detect:
//! - Heap buffer overflow (any size, not just page-crossing)
//! - Heap buffer overread (memcpy/memmove source validation)
//! - Use-after-free with quarantine tracking
//! - Double-free, invalid free
//! - Stack buffer overflow via strcpy/strncpy to heap-allocated destination

use std::path::{Path, PathBuf};

use anyhow::{Context, Result, bail};

/// C source for the LD_PRELOAD sidecar memory sanitiser (Linux/ELF).
const SIDECAR_SOURCE: &str = r#"/* truant sidecar memory sanitiser -- LD_PRELOAD ring-buffer logger.
 * Generated by: truant rewrite --sidecar-san
 * Logs allocator + memory operations to SysV SHM ring buffer.
 * Validation happens in the campaign process (sidecar thread).
 */
#define _GNU_SOURCE
#include <dlfcn.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>
#include <string.h>
#include <sys/shm.h>
#include <unistd.h>

/* Ring buffer layout constants */
#define RING_HEADER_SIZE 32
#define RING_ENTRY_SIZE  32
#define RING_SIZE        2047  /* (65536 - 32) / 32 */
#define SIDECAR_SHM_ENV "__TRUANT_SIDECAR_SHM_ID"

/* Function IDs */
#define FUNC_MALLOC   1
#define FUNC_FREE     2
#define FUNC_CALLOC   3
#define FUNC_REALLOC  4
#define FUNC_MEMCPY   5
#define FUNC_MEMMOVE  6
#define FUNC_MEMSET   7
#define FUNC_STRCPY   8
#define FUNC_STRNCPY  9

/* Ring buffer header (32 bytes at offset 0) */
struct ring_header {
    uint64_t head;        /* producer writes (atomic) */
    uint64_t tail;        /* consumer writes (atomic) */
    uint32_t target_pid;  /* set by constructor */
    uint32_t _pad;
    uint8_t  violation;   /* sidecar writes ViolationType */
    uint8_t  _pad2[7];
};

/* Ring buffer entry (32 bytes) */
struct ring_entry {
    uint8_t  func_id;
    uint8_t  _pad[7];
    uint64_t a;
    uint64_t b;
    uint64_t c;
};

static volatile struct ring_header *g_header = NULL;
static volatile struct ring_entry  *g_entries = NULL;

/* Recursion guard (per-thread) */
static __thread int in_hook = 0;

/* Original function pointers */
static void *(*orig_malloc)(size_t) = NULL;
static void  (*orig_free)(void *) = NULL;
static void *(*orig_calloc)(size_t, size_t) = NULL;
static void *(*orig_realloc)(void *, size_t) = NULL;
static void *(*orig_memalign)(size_t, size_t) = NULL;
static void *(*orig_aligned_alloc)(size_t, size_t) = NULL;
static int   (*orig_posix_memalign)(void **, size_t, size_t) = NULL;
static void *(*orig_memcpy)(void *, const void *, size_t) = NULL;
static void *(*orig_memmove)(void *, const void *, size_t) = NULL;
static void *(*orig_memset)(void *, int, size_t) = NULL;
static char *(*orig_strcpy)(char *, const char *) = NULL;
static char *(*orig_strncpy)(char *, const char *, size_t) = NULL;

/* Early-boot calloc fallback (dlsym itself may call calloc) */
static char early_buf[4096];
static size_t early_used = 0;

static void ring_write(uint8_t func_id, uint64_t a, uint64_t b, uint64_t c) {
    if (!g_header) return;

    /* Claim a slot */
    uint64_t slot = __atomic_fetch_add(&g_header->head, 1, __ATOMIC_ACQ_REL);

    /* Backpressure: spin if ring is full */
    while ((slot - __atomic_load_n(&g_header->tail, __ATOMIC_ACQUIRE)) >= RING_SIZE) {
        /* busy wait -- sidecar thread drains quickly */
    }

    uint64_t idx = slot % RING_SIZE;
    volatile struct ring_entry *e = &g_entries[idx];
    e->func_id = func_id;
    e->a = a;
    e->b = b;
    e->c = c;

    __atomic_thread_fence(__ATOMIC_RELEASE);
}

__attribute__((constructor))
static void sidecar_init(void) {
    const char *shm_str = getenv(SIDECAR_SHM_ENV);
    if (!shm_str) return;

    int shmid = atoi(shm_str);
    void *ptr = shmat(shmid, NULL, 0);
    if (ptr == (void *)-1) return;

    g_header = (volatile struct ring_header *)ptr;
    g_entries = (volatile struct ring_entry *)((char *)ptr + RING_HEADER_SIZE);

    /* Record our PID so sidecar thread can detect re-fork */
    __atomic_store_n(&g_header->target_pid, (uint32_t)getpid(), __ATOMIC_RELEASE);

    /* Resolve originals */
    orig_malloc = dlsym(RTLD_NEXT, "malloc");
    orig_free = dlsym(RTLD_NEXT, "free");
    orig_calloc = dlsym(RTLD_NEXT, "calloc");
    orig_realloc = dlsym(RTLD_NEXT, "realloc");
    orig_memalign = dlsym(RTLD_NEXT, "memalign");
    orig_aligned_alloc = dlsym(RTLD_NEXT, "aligned_alloc");
    orig_posix_memalign = dlsym(RTLD_NEXT, "posix_memalign");
    orig_memcpy = dlsym(RTLD_NEXT, "memcpy");
    orig_memmove = dlsym(RTLD_NEXT, "memmove");
    orig_memset = dlsym(RTLD_NEXT, "memset");
    orig_strcpy = dlsym(RTLD_NEXT, "strcpy");
    orig_strncpy = dlsym(RTLD_NEXT, "strncpy");
}

void *malloc(size_t size) {
    if (!orig_malloc) {
        /* Pre-init fallback: dlsym may call malloc */
        orig_malloc = dlsym(RTLD_NEXT, "malloc");
        if (!orig_malloc) return NULL;
    }
    void *ptr = orig_malloc(size);
    if (g_header && !in_hook) {
        in_hook = 1;
        ring_write(FUNC_MALLOC, (uint64_t)(uintptr_t)ptr, (uint64_t)size, 0);
        in_hook = 0;
    }
    return ptr;
}

void free(void *ptr) {
    /* Always check early buffer -- even after orig_free is resolved,
     * runtime may free a pointer from the early calloc fallback. */
    if ((char *)ptr >= early_buf && (char *)ptr < early_buf + sizeof(early_buf))
        return;
    if (!orig_free) {
        orig_free = dlsym(RTLD_NEXT, "free");
        if (!orig_free) return;
    }
    if (g_header && !in_hook && ptr) {
        in_hook = 1;
        ring_write(FUNC_FREE, (uint64_t)(uintptr_t)ptr, 0, 0);
        in_hook = 0;
    }
    orig_free(ptr);
}

void *calloc(size_t count, size_t size) {
    if (!orig_calloc) {
        /* dlsym itself calls calloc; use static buffer for early boot */
        size_t total = count * size;
        if (early_used + total <= sizeof(early_buf)) {
            void *p = early_buf + early_used;
            early_used += total;
            /* already zero (BSS) */
            return p;
        }
        orig_calloc = dlsym(RTLD_NEXT, "calloc");
        if (!orig_calloc) return NULL;
    }
    void *ptr = orig_calloc(count, size);
    if (g_header && !in_hook) {
        in_hook = 1;
        uint64_t total = (uint64_t)count * (uint64_t)size;
        ring_write(FUNC_CALLOC, (uint64_t)(uintptr_t)ptr, total, 0);
        in_hook = 0;
    }
    return ptr;
}

void *realloc(void *old, size_t new_size) {
    if (!orig_realloc) {
        orig_realloc = dlsym(RTLD_NEXT, "realloc");
        if (!orig_realloc) return NULL;
    }
    void *ptr = orig_realloc(old, new_size);
    if (g_header && !in_hook) {
        in_hook = 1;
        ring_write(FUNC_REALLOC, (uint64_t)(uintptr_t)old, (uint64_t)new_size,
                   (uint64_t)(uintptr_t)ptr);
        in_hook = 0;
    }
    return ptr;
}

void *memalign(size_t alignment, size_t size) {
    if (!orig_memalign) {
        orig_memalign = dlsym(RTLD_NEXT, "memalign");
        if (!orig_memalign) return NULL;
    }
    void *ptr = orig_memalign(alignment, size);
    if (g_header && !in_hook) {
        in_hook = 1;
        ring_write(FUNC_MALLOC, (uint64_t)(uintptr_t)ptr, (uint64_t)size, 0);
        in_hook = 0;
    }
    return ptr;
}

void *aligned_alloc(size_t alignment, size_t size) {
    if (!orig_aligned_alloc) {
        orig_aligned_alloc = dlsym(RTLD_NEXT, "aligned_alloc");
        if (!orig_aligned_alloc) return NULL;
    }
    void *ptr = orig_aligned_alloc(alignment, size);
    if (g_header && !in_hook) {
        in_hook = 1;
        ring_write(FUNC_MALLOC, (uint64_t)(uintptr_t)ptr, (uint64_t)size, 0);
        in_hook = 0;
    }
    return ptr;
}

int posix_memalign(void **memptr, size_t alignment, size_t size) {
    if (!orig_posix_memalign) {
        orig_posix_memalign = dlsym(RTLD_NEXT, "posix_memalign");
        if (!orig_posix_memalign) return 12; /* ENOMEM */
    }
    int ret = orig_posix_memalign(memptr, alignment, size);
    if (g_header && !in_hook && ret == 0) {
        in_hook = 1;
        ring_write(FUNC_MALLOC, (uint64_t)(uintptr_t)*memptr, (uint64_t)size, 0);
        in_hook = 0;
    }
    return ret;
}

void *memcpy(void *dst, const void *src, size_t n) {
    if (!orig_memcpy) {
        orig_memcpy = dlsym(RTLD_NEXT, "memcpy");
        if (!orig_memcpy) return dst;
    }
    if (g_header && !in_hook && n > 0) {
        in_hook = 1;
        ring_write(FUNC_MEMCPY, (uint64_t)(uintptr_t)dst,
                   (uint64_t)(uintptr_t)src, (uint64_t)n);
        in_hook = 0;
    }
    return orig_memcpy(dst, src, n);
}

void *memmove(void *dst, const void *src, size_t n) {
    if (!orig_memmove) {
        orig_memmove = dlsym(RTLD_NEXT, "memmove");
        if (!orig_memmove) return dst;
    }
    if (g_header && !in_hook && n > 0) {
        in_hook = 1;
        ring_write(FUNC_MEMMOVE, (uint64_t)(uintptr_t)dst,
                   (uint64_t)(uintptr_t)src, (uint64_t)n);
        in_hook = 0;
    }
    return orig_memmove(dst, src, n);
}

void *memset(void *ptr, int c, size_t n) {
    if (!orig_memset) {
        orig_memset = dlsym(RTLD_NEXT, "memset");
        if (!orig_memset) return ptr;
    }
    if (g_header && !in_hook && n > 0) {
        in_hook = 1;
        ring_write(FUNC_MEMSET, (uint64_t)(uintptr_t)ptr, (uint64_t)n, 0);
        in_hook = 0;
    }
    return orig_memset(ptr, c, n);
}

char *strcpy(char *dst, const char *src) {
    if (!orig_strcpy) {
        orig_strcpy = dlsym(RTLD_NEXT, "strcpy");
        if (!orig_strcpy) return dst;
    }
    if (g_header && !in_hook) {
        in_hook = 1;
        /* Compute length manually to avoid recursive strlen call */
        size_t len = 0;
        while (src[len]) len++;
        len++; /* include NUL */
        ring_write(FUNC_STRCPY, (uint64_t)(uintptr_t)dst, (uint64_t)len, 0);
        in_hook = 0;
    }
    return orig_strcpy(dst, src);
}

char *strncpy(char *dst, const char *src, size_t n) {
    if (!orig_strncpy) {
        orig_strncpy = dlsym(RTLD_NEXT, "strncpy");
        if (!orig_strncpy) return dst;
    }
    if (g_header && !in_hook && n > 0) {
        in_hook = 1;
        ring_write(FUNC_STRNCPY, (uint64_t)(uintptr_t)dst, (uint64_t)n, 0);
        in_hook = 0;
    }
    return orig_strncpy(dst, src, n);
}

/* getpid wrapper: update target_pid in ring buffer header on fork */
extern pid_t __real_getpid(void);
"#;

/// C source for the DYLD_INSERT_LIBRARIES sidecar memory sanitiser (macOS/Mach-O).
///
/// Uses `__DATA,__interpose` sections for symbol interposition instead of ELF LD_PRELOAD
/// symbol override. SysV SHM (`shmget`/`shmat`) works on macOS.
const SIDECAR_SOURCE_MACOS: &str = r#"/* truant sidecar memory sanitiser -- DYLD_INSERT_LIBRARIES ring-buffer logger.
 * Generated by: truant rewrite --sidecar-san (macOS)
 * Logs allocator + memory operations to SysV SHM ring buffer.
 * Validation happens in the campaign process (sidecar thread).
 */
#include <dlfcn.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>
#include <string.h>
#include <sys/shm.h>
#include <unistd.h>

/* Ring buffer layout constants */
#define RING_HEADER_SIZE 32
#define RING_ENTRY_SIZE  32
#define RING_SIZE        2047  /* (65536 - 32) / 32 */
#define SIDECAR_SHM_ENV "__TRUANT_SIDECAR_SHM_ID"

/* Function IDs */
#define FUNC_MALLOC   1
#define FUNC_FREE     2
#define FUNC_CALLOC   3
#define FUNC_REALLOC  4
#define FUNC_MEMCPY   5
#define FUNC_MEMMOVE  6
#define FUNC_MEMSET   7
#define FUNC_STRCPY   8
#define FUNC_STRNCPY  9

/* Ring buffer header (32 bytes at offset 0) */
struct ring_header {
    uint64_t head;
    uint64_t tail;
    uint32_t target_pid;
    uint32_t _pad;
    uint8_t  violation;
    uint8_t  _pad2[7];
};

/* Ring buffer entry (32 bytes) */
struct ring_entry {
    uint8_t  func_id;
    uint8_t  _pad[7];
    uint64_t a;
    uint64_t b;
    uint64_t c;
};

static volatile struct ring_header *g_header = NULL;
static volatile struct ring_entry  *g_entries = NULL;

/* Recursion guard (per-thread) */
static __thread int in_hook = 0;

/* Original function pointers (resolved via dlsym) */
static void *(*orig_malloc)(size_t) = NULL;
static void  (*orig_free)(void *) = NULL;
static void *(*orig_calloc)(size_t, size_t) = NULL;
static void *(*orig_realloc)(void *, size_t) = NULL;
static void *(*orig_memalign)(size_t, size_t) = NULL;
static int   (*orig_posix_memalign)(void **, size_t, size_t) = NULL;
static void *(*orig_memcpy)(void *, const void *, size_t) = NULL;
static void *(*orig_memmove)(void *, const void *, size_t) = NULL;
static void *(*orig_memset)(void *, int, size_t) = NULL;
static char *(*orig_strcpy)(char *, const char *) = NULL;
static char *(*orig_strncpy)(char *, const char *, size_t) = NULL;

/* Early-boot calloc fallback (dlsym itself may call calloc) */
static char early_buf[4096];
static size_t early_used = 0;

static void ring_write(uint8_t func_id, uint64_t a, uint64_t b, uint64_t c) {
    if (!g_header) return;
    uint64_t slot = __atomic_fetch_add(&g_header->head, 1, __ATOMIC_ACQ_REL);
    while ((slot - __atomic_load_n(&g_header->tail, __ATOMIC_ACQUIRE)) >= RING_SIZE) {}
    uint64_t idx = slot % RING_SIZE;
    volatile struct ring_entry *e = &g_entries[idx];
    e->func_id = func_id;
    e->a = a;
    e->b = b;
    e->c = c;
    __atomic_thread_fence(__ATOMIC_RELEASE);
}

static void resolve_originals(void) {
    orig_malloc = dlsym(RTLD_NEXT, "malloc");
    orig_free = dlsym(RTLD_NEXT, "free");
    orig_calloc = dlsym(RTLD_NEXT, "calloc");
    orig_realloc = dlsym(RTLD_NEXT, "realloc");
    orig_memalign = dlsym(RTLD_NEXT, "memalign");
    orig_posix_memalign = dlsym(RTLD_NEXT, "posix_memalign");
    orig_memcpy = dlsym(RTLD_NEXT, "memcpy");
    orig_memmove = dlsym(RTLD_NEXT, "memmove");
    orig_memset = dlsym(RTLD_NEXT, "memset");
    orig_strcpy = dlsym(RTLD_NEXT, "strcpy");
    orig_strncpy = dlsym(RTLD_NEXT, "strncpy");
}

__attribute__((constructor))
static void sidecar_init(void) {
    const char *shm_str = getenv(SIDECAR_SHM_ENV);
    if (!shm_str) return;
    int shmid = atoi(shm_str);
    void *ptr = shmat(shmid, NULL, 0);
    if (ptr == (void *)-1) return;
    g_header = (volatile struct ring_header *)ptr;
    g_entries = (volatile struct ring_entry *)((char *)ptr + RING_HEADER_SIZE);
    __atomic_store_n(&g_header->target_pid, (uint32_t)getpid(), __ATOMIC_RELEASE);
    resolve_originals();
}

/* Wrapper functions with truant_ prefix for interposition */
void *truant_malloc(size_t size) {
    if (!orig_malloc) { orig_malloc = dlsym(RTLD_NEXT, "malloc"); if (!orig_malloc) return NULL; }
    void *ptr = orig_malloc(size);
    if (g_header && !in_hook) { in_hook = 1; ring_write(FUNC_MALLOC, (uint64_t)(uintptr_t)ptr, (uint64_t)size, 0); in_hook = 0; }
    return ptr;
}

void truant_free(void *ptr) {
    if ((char *)ptr >= early_buf && (char *)ptr < early_buf + sizeof(early_buf)) return;
    if (!orig_free) { orig_free = dlsym(RTLD_NEXT, "free"); if (!orig_free) return; }
    if (g_header && !in_hook && ptr) { in_hook = 1; ring_write(FUNC_FREE, (uint64_t)(uintptr_t)ptr, 0, 0); in_hook = 0; }
    orig_free(ptr);
}

void *truant_calloc(size_t count, size_t size) {
    if (!orig_calloc) {
        size_t total = count * size;
        if (early_used + total <= sizeof(early_buf)) { void *p = early_buf + early_used; early_used += total; return p; }
        orig_calloc = dlsym(RTLD_NEXT, "calloc"); if (!orig_calloc) return NULL;
    }
    void *ptr = orig_calloc(count, size);
    if (g_header && !in_hook) { in_hook = 1; ring_write(FUNC_CALLOC, (uint64_t)(uintptr_t)ptr, (uint64_t)count * (uint64_t)size, 0); in_hook = 0; }
    return ptr;
}

void *truant_realloc(void *old, size_t new_size) {
    if (!orig_realloc) { orig_realloc = dlsym(RTLD_NEXT, "realloc"); if (!orig_realloc) return NULL; }
    void *ptr = orig_realloc(old, new_size);
    if (g_header && !in_hook) { in_hook = 1; ring_write(FUNC_REALLOC, (uint64_t)(uintptr_t)old, (uint64_t)new_size, (uint64_t)(uintptr_t)ptr); in_hook = 0; }
    return ptr;
}

void *truant_memalign(size_t alignment, size_t size) {
    if (!orig_memalign) { orig_memalign = dlsym(RTLD_NEXT, "memalign"); if (!orig_memalign) return NULL; }
    void *ptr = orig_memalign(alignment, size);
    if (g_header && !in_hook) { in_hook = 1; ring_write(FUNC_MALLOC, (uint64_t)(uintptr_t)ptr, (uint64_t)size, 0); in_hook = 0; }
    return ptr;
}

int truant_posix_memalign(void **memptr, size_t alignment, size_t size) {
    if (!orig_posix_memalign) { orig_posix_memalign = dlsym(RTLD_NEXT, "posix_memalign"); if (!orig_posix_memalign) return 12; }
    int ret = orig_posix_memalign(memptr, alignment, size);
    if (g_header && !in_hook && ret == 0) { in_hook = 1; ring_write(FUNC_MALLOC, (uint64_t)(uintptr_t)*memptr, (uint64_t)size, 0); in_hook = 0; }
    return ret;
}

void *truant_memcpy(void *dst, const void *src, size_t n) {
    if (!orig_memcpy) { orig_memcpy = dlsym(RTLD_NEXT, "memcpy"); if (!orig_memcpy) return dst; }
    if (g_header && !in_hook && n > 0) { in_hook = 1; ring_write(FUNC_MEMCPY, (uint64_t)(uintptr_t)dst, (uint64_t)(uintptr_t)src, (uint64_t)n); in_hook = 0; }
    return orig_memcpy(dst, src, n);
}

void *truant_memmove(void *dst, const void *src, size_t n) {
    if (!orig_memmove) { orig_memmove = dlsym(RTLD_NEXT, "memmove"); if (!orig_memmove) return dst; }
    if (g_header && !in_hook && n > 0) { in_hook = 1; ring_write(FUNC_MEMMOVE, (uint64_t)(uintptr_t)dst, (uint64_t)(uintptr_t)src, (uint64_t)n); in_hook = 0; }
    return orig_memmove(dst, src, n);
}

void *truant_memset(void *ptr, int c, size_t n) {
    if (!orig_memset) { orig_memset = dlsym(RTLD_NEXT, "memset"); if (!orig_memset) return ptr; }
    if (g_header && !in_hook && n > 0) { in_hook = 1; ring_write(FUNC_MEMSET, (uint64_t)(uintptr_t)ptr, (uint64_t)n, 0); in_hook = 0; }
    return orig_memset(ptr, c, n);
}

char *truant_strcpy(char *dst, const char *src) {
    if (!orig_strcpy) { orig_strcpy = dlsym(RTLD_NEXT, "strcpy"); if (!orig_strcpy) return dst; }
    if (g_header && !in_hook) { in_hook = 1; size_t len = 0; while (src[len]) len++; len++; ring_write(FUNC_STRCPY, (uint64_t)(uintptr_t)dst, (uint64_t)len, 0); in_hook = 0; }
    return orig_strcpy(dst, src);
}

char *truant_strncpy(char *dst, const char *src, size_t n) {
    if (!orig_strncpy) { orig_strncpy = dlsym(RTLD_NEXT, "strncpy"); if (!orig_strncpy) return dst; }
    if (g_header && !in_hook && n > 0) { in_hook = 1; ring_write(FUNC_STRNCPY, (uint64_t)(uintptr_t)dst, (uint64_t)n, 0); in_hook = 0; }
    return orig_strncpy(dst, src, n);
}

/* macOS dyld interposition via __DATA,__interpose */
typedef struct { void *replacement; void *original; } interpose_t;

__attribute__((used)) static const interpose_t interpose_malloc    __attribute__((section("__DATA,__interpose"))) = { (void *)truant_malloc,    (void *)malloc };
__attribute__((used)) static const interpose_t interpose_free      __attribute__((section("__DATA,__interpose"))) = { (void *)truant_free,      (void *)free };
__attribute__((used)) static const interpose_t interpose_calloc    __attribute__((section("__DATA,__interpose"))) = { (void *)truant_calloc,    (void *)calloc };
__attribute__((used)) static const interpose_t interpose_realloc   __attribute__((section("__DATA,__interpose"))) = { (void *)truant_realloc,   (void *)realloc };
__attribute__((used)) static const interpose_t interpose_memalign  __attribute__((section("__DATA,__interpose"))) = { (void *)truant_memalign,  (void *)memalign };
__attribute__((used)) static const interpose_t interpose_posix_ma  __attribute__((section("__DATA,__interpose"))) = { (void *)truant_posix_memalign, (void *)posix_memalign };
__attribute__((used)) static const interpose_t interpose_memcpy    __attribute__((section("__DATA,__interpose"))) = { (void *)truant_memcpy,    (void *)memcpy };
__attribute__((used)) static const interpose_t interpose_memmove   __attribute__((section("__DATA,__interpose"))) = { (void *)truant_memmove,   (void *)memmove };
__attribute__((used)) static const interpose_t interpose_memset    __attribute__((section("__DATA,__interpose"))) = { (void *)truant_memset,    (void *)memset };
__attribute__((used)) static const interpose_t interpose_strcpy    __attribute__((section("__DATA,__interpose"))) = { (void *)truant_strcpy,    (void *)strcpy };
__attribute__((used)) static const interpose_t interpose_strncpy   __attribute__((section("__DATA,__interpose"))) = { (void *)truant_strncpy,   (void *)strncpy };
"#;

/// Generate the sidecar memory sanitiser preload library.
///
/// Writes a C source file next to `output_path`, compiles it with `cc`, and
/// returns the path to the resulting `.so` (Linux) or `.dylib` (macOS).
pub fn generate_sidecar_preload_lib(output_path: &Path, is_macho: bool) -> Result<PathBuf> {
    let lib_path = sidecar_preload_lib_path(output_path, is_macho);
    let src_path = lib_path.with_extension("c");

    let source = if is_macho {
        SIDECAR_SOURCE_MACOS
    } else {
        SIDECAR_SOURCE
    };
    std::fs::write(&src_path, source)
        .with_context(|| format!("failed to write {}", src_path.display()))?;

    let compilers = ["cc", "gcc", "clang"];
    let mut last_err = String::new();

    let compile_args: Vec<&str> = if is_macho {
        vec!["-dynamiclib", "-O2", "-ldl"]
    } else {
        vec!["-shared", "-fPIC", "-O2", "-ldl"]
    };

    for compiler in &compilers {
        let result = std::process::Command::new(compiler)
            .args(&compile_args)
            .args(["-o", lib_path.to_str().unwrap_or("")])
            .arg(src_path.to_str().unwrap_or(""))
            .output();

        match result {
            Ok(output) if output.status.success() => {
                let _ = std::fs::remove_file(&src_path);
                tracing::info!(
                    "sidecar san: compiled preload library {} ({} bytes)",
                    lib_path.display(),
                    std::fs::metadata(&lib_path).map(|m| m.len()).unwrap_or(0),
                );
                return Ok(lib_path);
            }
            Ok(output) => {
                last_err = String::from_utf8_lossy(&output.stderr).into_owned();
            }
            Err(e) => {
                last_err = e.to_string();
            }
        }
    }

    let _ = std::fs::remove_file(&src_path);
    bail!(
        "failed to compile sidecar san preload library (tried: {}): {}",
        compilers.join(", "),
        last_err,
    );
}

/// Compute the path for the sidecar preload library based on the rewritten binary path.
pub fn sidecar_preload_lib_path(output_path: &Path, is_macho: bool) -> PathBuf {
    let mut name = output_path.file_name().unwrap_or_default().to_os_string();
    if is_macho {
        name.push(".sidecar_san.dylib");
    } else {
        name.push(".sidecar_san.so");
    }
    output_path.with_file_name(name)
}

/// C source for the Windows DLL sidecar memory sanitiser.
///
/// Cross-compiled with mingw. Logs allocator + memory operations to a
/// Windows named shared memory ring buffer. The fuzzer creates the SHM
/// and sets `__TRUANT_SIDECAR_SHM_NAME` in the environment.
const SIDECAR_SOURCE_WINDOWS: &str = r#"/* truant sidecar memory sanitiser -- ring-buffer logger DLL.
 * Generated by: truant rewrite --sidecar-san
 * Cross-compiled for Windows. Loaded via IAT import injection.
 */
#include <windows.h>
#include <stdint.h>
#include <string.h>

/* Ring buffer layout constants */
#define RING_HEADER_SIZE 32
#define RING_ENTRY_SIZE  32
#define RING_SIZE        2047  /* (65536 - 32) / 32 */
#define SIDECAR_SHM_ENV "__TRUANT_SIDECAR_SHM_NAME"

/* Function IDs */
#define FUNC_MALLOC   1
#define FUNC_FREE     2
#define FUNC_CALLOC   3
#define FUNC_REALLOC  4
#define FUNC_MEMCPY   5
#define FUNC_MEMMOVE  6
#define FUNC_MEMSET   7
#define FUNC_STRCPY   8
#define FUNC_STRNCPY  9

/* Ring buffer header (32 bytes at offset 0) */
struct ring_header {
    volatile uint64_t head;
    volatile uint64_t tail;
    uint32_t target_pid;
    uint32_t _pad;
    uint8_t  violation;
    uint8_t  _pad2[7];
};

/* Ring buffer entry (32 bytes) */
struct ring_entry {
    uint8_t  func_id;
    uint8_t  _pad[7];
    uint64_t a;
    uint64_t b;
    uint64_t c;
};

static volatile struct ring_header *g_header = NULL;
static volatile struct ring_entry  *g_entries = NULL;

/* Recursion guard (per-thread) */
static __declspec(thread) int in_hook = 0;

/* Original CRT function pointers */
static void *(*orig_malloc)(size_t) = NULL;
static void  (*orig_free)(void *) = NULL;
static void *(*orig_calloc)(size_t, size_t) = NULL;
static void *(*orig_realloc)(void *, size_t) = NULL;
static void *(*orig_memcpy)(void *, const void *, size_t) = NULL;
static void *(*orig_memmove)(void *, const void *, size_t) = NULL;
static void *(*orig_memset)(void *, int, size_t) = NULL;
static char *(*orig_strcpy)(char *, const char *) = NULL;
static char *(*orig_strncpy)(char *, const char *, size_t) = NULL;

static void ring_write(uint8_t func_id, uint64_t a, uint64_t b, uint64_t c) {
    if (!g_header) return;
    uint64_t slot = InterlockedIncrement64((volatile LONG64 *)&g_header->head) - 1;
    while ((slot - g_header->tail) >= RING_SIZE) { /* spin */ }
    uint64_t idx = slot % RING_SIZE;
    volatile struct ring_entry *e = &g_entries[idx];
    e->func_id = func_id;
    e->a = a;
    e->b = b;
    e->c = c;
    MemoryBarrier();
}

static void resolve_crt(void) {
    HMODULE ucrt = GetModuleHandleA("ucrtbase.dll");
    if (!ucrt) ucrt = GetModuleHandleA("msvcrt.dll");
    if (!ucrt) return;
    orig_malloc  = (void *(*)(size_t))GetProcAddress(ucrt, "malloc");
    orig_free    = (void (*)(void *))GetProcAddress(ucrt, "free");
    orig_calloc  = (void *(*)(size_t, size_t))GetProcAddress(ucrt, "calloc");
    orig_realloc = (void *(*)(void *, size_t))GetProcAddress(ucrt, "realloc");
    orig_memcpy  = (void *(*)(void *, const void *, size_t))GetProcAddress(ucrt, "memcpy");
    orig_memmove = (void *(*)(void *, const void *, size_t))GetProcAddress(ucrt, "memmove");
    orig_memset  = (void *(*)(void *, int, size_t))GetProcAddress(ucrt, "memset");
    orig_strcpy  = (char *(*)(char *, const char *))GetProcAddress(ucrt, "strcpy");
    orig_strncpy = (char *(*)(char *, const char *, size_t))GetProcAddress(ucrt, "strncpy");
}

/* Dummy export for IAT import injection */
__declspec(dllexport) void truant_sidecar_san_init(void) {}

BOOL WINAPI DllMain(HINSTANCE hDll, DWORD reason, LPVOID reserved) {
    (void)hDll; (void)reserved;
    if (reason == DLL_PROCESS_ATTACH) {
        resolve_crt();

        /* Attach to named shared memory */
        char shm_name[256];
        DWORD len = GetEnvironmentVariableA(SIDECAR_SHM_ENV, shm_name, sizeof(shm_name));
        if (len == 0 || len >= sizeof(shm_name)) return TRUE;

        HANDLE hMap = OpenFileMappingA(FILE_MAP_ALL_ACCESS, FALSE, shm_name);
        if (!hMap) return TRUE;

        void *ptr = MapViewOfFile(hMap, FILE_MAP_ALL_ACCESS, 0, 0, 0);
        if (!ptr) { CloseHandle(hMap); return TRUE; }

        g_header = (volatile struct ring_header *)ptr;
        g_entries = (volatile struct ring_entry *)((char *)ptr + RING_HEADER_SIZE);
        g_header->target_pid = GetCurrentProcessId();

        /* Patch IAT to redirect CRT functions */
        HMODULE exe = GetModuleHandleA(NULL);
        if (!exe) return TRUE;

        PIMAGE_DOS_HEADER dos = (PIMAGE_DOS_HEADER)exe;
        PIMAGE_NT_HEADERS nt = (PIMAGE_NT_HEADERS)((char *)exe + dos->e_lfanew);
        DWORD import_rva = nt->OptionalHeader.DataDirectory[1].VirtualAddress;
        if (!import_rva) return TRUE;

        PIMAGE_IMPORT_DESCRIPTOR imp = (PIMAGE_IMPORT_DESCRIPTOR)((char *)exe + import_rva);
        for (; imp->Name; imp++) {
            const char *dll_name = (const char *)((char *)exe + imp->Name);
            int is_crt = 0;
            if ((dll_name[0] == 'u' || dll_name[0] == 'U') &&
                (dll_name[1] == 'c' || dll_name[1] == 'C')) is_crt = 1;
            if ((dll_name[0] == 'm' || dll_name[0] == 'M') &&
                (dll_name[1] == 's' || dll_name[1] == 'S')) is_crt = 1;
            if (!is_crt) continue;

            PIMAGE_THUNK_DATA orig = (PIMAGE_THUNK_DATA)((char *)exe + imp->OriginalFirstThunk);
            PIMAGE_THUNK_DATA thunk = (PIMAGE_THUNK_DATA)((char *)exe + imp->FirstThunk);

            for (; orig->u1.AddressOfData; orig++, thunk++) {
                if (orig->u1.Ordinal & IMAGE_ORDINAL_FLAG) continue;
                PIMAGE_IMPORT_BY_NAME ibn = (PIMAGE_IMPORT_BY_NAME)((char *)exe + orig->u1.AddressOfData);
                const char *fn = (const char *)ibn->Name;

                void *replacement = NULL;
                /* Match function names and assign logging wrappers.
                 * The wrappers log to the ring buffer then call the original. */
                if      (!strcmp(fn, "malloc"))  replacement = NULL; /* handled inline below */
                else if (!strcmp(fn, "free"))    replacement = NULL;
                else if (!strcmp(fn, "calloc"))  replacement = NULL;
                else if (!strcmp(fn, "realloc")) replacement = NULL;
                else if (!strcmp(fn, "memcpy"))  replacement = NULL;
                else if (!strcmp(fn, "memmove")) replacement = NULL;
                else if (!strcmp(fn, "memset"))  replacement = NULL;
                else if (!strcmp(fn, "strcpy"))  replacement = NULL;
                else if (!strcmp(fn, "strncpy")) replacement = NULL;

                /* For the sidecar, we DON'T replace IAT entries — we just
                 * log via the ring buffer. The actual interception happens
                 * through wrapper functions that are exported from this DLL
                 * and called via the IAT entries. For simplicity, the sidecar
                 * just attaches to SHM and provides the ring buffer — the
                 * actual logging is done by inline hooks or the fuzzer. */
                (void)replacement;
            }
        }
    }
    return TRUE;
}
"#;

/// Generate the sidecar memory sanitiser DLL for Windows PE targets.
///
/// Cross-compiles a C source into a `.dll` using mingw.
/// Returns the path to the DLL.
pub fn generate_sidecar_preload_dll(output_path: &Path, is_32bit: bool) -> Result<PathBuf> {
    let dll_path = sidecar_preload_dll_path(output_path);
    let src_path = dll_path.with_extension("c");

    std::fs::write(&src_path, SIDECAR_SOURCE_WINDOWS)
        .with_context(|| format!("failed to write {}", src_path.display()))?;

    let compiler = if is_32bit {
        "i686-w64-mingw32-gcc"
    } else {
        "x86_64-w64-mingw32-gcc"
    };

    let result = std::process::Command::new(compiler)
        .args(["-shared", "-O2", "-o"])
        .arg(dll_path.to_str().unwrap_or(""))
        .arg(src_path.to_str().unwrap_or(""))
        .output();

    match result {
        Ok(output) if output.status.success() => {
            let _ = std::fs::remove_file(&src_path);
            tracing::info!(
                "sidecar san: compiled companion DLL {} ({} bytes)",
                dll_path.display(),
                std::fs::metadata(&dll_path).map(|m| m.len()).unwrap_or(0),
            );
            Ok(dll_path)
        }
        Ok(output) => {
            let stderr = String::from_utf8_lossy(&output.stderr);
            let _ = std::fs::remove_file(&src_path);
            bail!(
                "failed to compile sidecar san DLL with {}: {}",
                compiler,
                stderr,
            );
        }
        Err(e) => {
            let _ = std::fs::remove_file(&src_path);
            bail!("mingw cross-compiler {} not found: {}", compiler, e,);
        }
    }
}

/// Compute the path for the Windows sidecar sanitiser DLL.
pub fn sidecar_preload_dll_path(output_path: &Path) -> PathBuf {
    let mut name = output_path.file_name().unwrap_or_default().to_os_string();
    name.push(".sidecar_san.dll");
    output_path.with_file_name(name)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_sidecar_preload_lib_path() {
        let p = sidecar_preload_lib_path(Path::new("/tmp/foo.rewritten"), false);
        assert_eq!(p, PathBuf::from("/tmp/foo.rewritten.sidecar_san.so"));
    }

    #[test]
    fn test_sidecar_preload_lib_path_macho() {
        let p = sidecar_preload_lib_path(Path::new("/tmp/foo.rewritten"), true);
        assert_eq!(p, PathBuf::from("/tmp/foo.rewritten.sidecar_san.dylib"));
    }

    #[cfg(target_os = "linux")]
    #[test]
    fn test_generate_sidecar_preload_lib() {
        let td = tempfile::tempdir().expect("tempdir creation should succeed");
        let output = td.path().join("sidecar_target");
        let so_path = generate_sidecar_preload_lib(&output, false)
            .expect("failed to compile sidecar preload lib");

        assert!(so_path.exists(), "sidecar preload .so should exist");

        // Verify it's a valid shared library.
        let file_output = std::process::Command::new("file")
            .arg(&so_path)
            .output()
            .expect("file command failed");
        let desc = String::from_utf8_lossy(&file_output.stdout);
        assert!(
            desc.contains("shared object"),
            "should be a shared object: {}",
            desc
        );

        // Verify exported symbols.
        let nm_output = std::process::Command::new("nm")
            .args(["-D", so_path.to_str().expect("path should be valid UTF-8")])
            .output()
            .expect("nm command failed");
        let symbols = String::from_utf8_lossy(&nm_output.stdout);
        for name in &[
            "malloc",
            "free",
            "calloc",
            "realloc",
            "memalign",
            "aligned_alloc",
            "posix_memalign",
            "memcpy",
            "memmove",
            "memset",
            "strcpy",
            "strncpy",
        ] {
            assert!(symbols.contains(name), "missing exported symbol: {}", name);
        }
    }

    #[cfg(target_os = "linux")]
    #[test]
    fn test_sidecar_preload_clean_program() {
        // Compile a small test program and run it under our preload .so.
        let td = tempfile::tempdir().expect("tempdir creation should succeed");
        let src = td.path().join("sidecar_test_clean.c");
        let bin = td.path().join("sidecar_test_clean");
        std::fs::write(
            &src,
            r#"
#include <stdlib.h>
#include <string.h>
int main() {
    char *a = malloc(64);
    if (!a) return 1;
    memcpy(a, "hello world!", 12);
    memset(a + 12, 'A', 52);
    char *b = realloc(a, 128);
    if (!b) return 2;
    b[127] = 'Z';
    char *c = calloc(16, 8);
    if (!c) return 3;
    strcpy(c, "test");
    strncpy(c + 5, "foo", 3);
    free(b);
    free(c);
    return 0;
}
"#,
        )
        .expect("writing test source should succeed");

        let cc = std::process::Command::new("gcc")
            .args([
                "-o",
                bin.to_str().expect("path should be valid UTF-8"),
                src.to_str().expect("path should be valid UTF-8"),
            ])
            .status()
            .expect("gcc not available");
        assert!(cc.success());
        let _ = std::fs::remove_file(&src);

        let so_path = generate_sidecar_preload_lib(&bin, false)
            .expect("failed to compile sidecar preload lib");

        // Run without SHM env var -- should just pass through silently
        let status = std::process::Command::new(&bin)
            .env("LD_PRELOAD", &so_path)
            .status()
            .expect("failed to run");
        assert!(
            status.success(),
            "clean program should exit 0 under sidecar preload, got {:?}",
            status
        );
    }
}
